# -*- coding: utf-8 -*-

"""
/***************************************************************************
 GeoCAR
                                 A QGIS plugin
Cadastro Ambiental Rural (CAR)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-27
        copyright            : (C) 2026 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Prof Cazaroli e Leandro França'
__date__ = '2026-02-27'
__copyright__ = '(C) 2026 by Prof Cazaroli e Leandro França'

# -*- coding: utf-8 -*-

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import *
from qgis import processing
from qgis.PyQt.QtGui import QIcon, QColor
from geocar.images.Imgs import *
import os

class declividade_25_45(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterRasterLayer('mdt', 'MDT', defaultValue=None))
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                'area_do_imovel',
                'Área do imóvel',
                types=[QgsProcessing.TypeVectorPolygon],
                defaultValue=None
            )
        )

        self.addParameter(QgsProcessingParameterCrs('src', 'SRC (projetado)', defaultValue='EPSG:31983'))

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                'Declividade2545',
                'Declividade entre 25° e 45°',
                type=QgsProcessing.TypeVectorAnyGeometry,
                createByDefault=True,
                defaultValue=None
            )
        )

    # Validações
    def _check_lftools_installed(self):
        """Verifica se o algoritmo do LFTools está disponível no Processing."""
        try:
            processing.algorithmHelp('lftools:binarythresholding')
        except Exception:
            raise QgsProcessingException(
                "O plugin LFTools não foi encontrado no Processing.\n"
                "Instale/ative o LFTools e reinicie o QGIS. (Algoritmo esperado: lftools:binarythresholding)"
            )

    def _check_projected_crs(self, crs: QgsCoordinateReferenceSystem):
        """Verifica se CRS é projetado (unidade em metros)."""
        if not crs or not crs.isValid():
            raise QgsProcessingException("SRC inválido. Selecione um SRC projetado (ex.: UTM).")

        # Preferir validação por tipo + unidade
        if crs.isGeographic():
            raise QgsProcessingException(
                f"O SRC escolhido ({crs.authid()}) NÃO é projetado.\n"
                "Para declividade (slope) e recortes por altitude, use um SRC projetado (ex.: UTM/SIRGAS 2000).\n"
                "Ex.: EPSG:31983 / EPSG:31984 / EPSG:32724 etc."
            )

    def processAlgorithm(self, parameters, context, model_feedback):
        feedback = QgsProcessingMultiStepFeedback(6, model_feedback)
        results = {}
        outputs = {}

        # -------------------------
        # Validações
        # -------------------------
        self._check_lftools_installed()

        target_crs = self.parameterAsCrs(parameters, 'src', context)
        self._check_projected_crs(target_crs)

        # -------------------------
        # Reprojetar MDT
        # -------------------------
        alg_params = {
            'DATA_TYPE': 0,
            'EXTRA': None,
            'INPUT': parameters['mdt'],
            'MULTITHREADING': False,
            'NODATA': None,
            'OPTIONS': None,
            'RESAMPLING': 2,
            'SOURCE_CRS': None,
            'TARGET_CRS': target_crs,
            'TARGET_EXTENT': None,
            'TARGET_EXTENT_CRS': None,
            'TARGET_RESOLUTION': None,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }

        outputs['ReprojetarCoordenadas'] = processing.run(
            'gdal:warpreproject',
            alg_params,
            context=context,
            feedback=feedback,
            is_child_algorithm=True
        )

        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}

        # -------------------------
        # Declividade
        # -------------------------
        alg_params = {
            'INPUT': outputs['ReprojetarCoordenadas']['OUTPUT'],
            'Z_FACTOR': 1,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }

        outputs['Declividade'] = processing.run(
            'native:slope',
            alg_params,
            context=context,
            feedback=feedback,
            is_child_algorithm=True
        )

        feedback.setCurrentStep(2)
        if feedback.isCanceled():
            return {}

        # -------------------------
        # Raster Calculator
        # Declividade entre 25 e 45 graus
        # -------------------------

        alg_params = {
            'INPUT_A': outputs['Declividade']['OUTPUT'],
            'BAND_A': 1,
            'FORMULA': '(A>=25)*(A<=45)',
            'NO_DATA': 0,
            'RTYPE': 5,
            'OPTIONS': '',
            'EXTRA': '',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }

        outputs['FaixaDeclividade'] = processing.run(
            'gdal:rastercalculator',
            alg_params,
            context=context,
            feedback=feedback,
            is_child_algorithm=True
        )

        # -------------------------
        # Polygonize
        # -------------------------
        alg_params = {
            'BAND': 1,
            'EIGHT_CONNECTEDNESS': False,
            'EXTRA': None,
            'FIELD': 'DN',
            'INPUT': outputs['FaixaDeclividade']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }

        outputs['PolygonizeSlope'] = processing.run(
            'gdal:polygonize',
            alg_params,
            context=context,
            feedback=feedback,
            is_child_algorithm=True
        )

        feedback.setCurrentStep(4)
        if feedback.isCanceled():
            return {}

        # -------------------------
        # Extrair DN = 1
        # -------------------------
        alg_params = {
            'FIELD': 'DN',
            'INPUT': outputs['PolygonizeSlope']['OUTPUT'],
            'OPERATOR': 0,
            'VALUE': '1',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }

        outputs['ExtractSlope'] = processing.run(
            'native:extractbyattribute',
            alg_params,
            context=context,
            feedback=feedback,
            is_child_algorithm=True
        )

        feedback.setCurrentStep(5)
        if feedback.isCanceled():
            return {}

        # -------------------------
        # Clip na área do imóvel
        # -------------------------
        out_param_slope = parameters['Declividade25a45']

        if not isinstance(out_param_slope, QgsProcessingOutputLayerDefinition):
            output_slope = QgsProcessingOutputLayerDefinition(
                out_param_slope,
                context.project()
            )
        else:
            output_slope = out_param_slope

        output_slope.destinationName = 'Declividade_25_45'

        alg_params = {
            'INPUT': outputs['ExtractSlope']['OUTPUT'],
            'OVERLAY': parameters['area_do_imovel'],
            'OUTPUT': output_slope
        }

        outputs['ClipSlope'] = processing.run(
            'native:clip',
            alg_params,
            context=context,
            feedback=feedback,
            is_child_algorithm=True
        )

        results['Declividade25a45'] = outputs['ClipSlope']['OUTPUT']

        self.output_slope_id = outputs['ClipSlope']['OUTPUT']

        return results
    
    def name(self):
        return 'declividade_entre_25_45'

    def displayName(self):
        return '3. Declividade entre 25° e 45°'

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def createInstance(self):
        return declividade_25_45()

    def tags(self):
        return 'GeoOne,GeoCAR,GeoRural,ambiental,APP,SiCAR,slope,inclinação,rampa,altura,elevação,MDE,MDT'.split(',')
    
    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/geocar.png'))

    def shortHelpString(self):
        txt = """Identifica áreas com <b>declividade entre 45° e 25°</b> a partir de um Modelo Digital do Terreno (MDT).

A ferramenta calcula automaticamente a declividade do MDT, classifica os valores acima dos limites definidos e gera polígonos recortados pela <b>área do imóvel</b>, permitindo delimitar regiões que podem corresponder a <b>Áreas de Preservação Permanente (APP)</b>.

<b>Parâmetros principais:</b>
• MDT – raster do Modelo Digital do Terreno  
• Área do imóvel – limite utilizado para recorte da análise  
• SRC (projetado) – sistema de coordenadas em metros (ex.: UTM)

<b>Resultado:</b>
São geradas duas camadas vetoriais: 
• <b>Declividade entre 25° e 45°</b>

<b>Observação:</b>
O processamento requer um <b>SRC projetado</b> (ex.: UTM) e o plugin <b>LFTools</b> instalado no QGIS.
"""

        footer = '''<div>
                      <div align="center">
                      <img style="width: 100%; height: auto;" src="data:image/jpg;base64,'''+ CAR_GeoOne +'''
                      </div>
                      <div align="right">
                      <p align="right">
                      <a href="https://geoone.com.br/pvcar/"><span style="font-weight: bold;">Conheça o curso de Cadastro Ambiental Rural (CAR)</span></a>
                      </p>
                      <p align="right">
                      <a href="https://portal.geoone.com.br/m/lessons/car?classId=6080"><span style="font-weight: bold;">Acesse a aula sobre esta ferramenta no curso de CAR da GeoOne</span></a>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
                      <p><i>"Mapeamento automatizado, fácil e direto ao ponto é na GeoOne!"</i></p>
                      </div>
                    </div>'''
        return txt + footer
    
    def postProcessAlgorithm(self, context, feedback):
        layer = QgsProcessingUtils.mapLayerFromString(self.output_id, context)
        if layer:
            # Estilo: Hachura azul para identificar a faixa
            hachura = QgsLinePatternFillSymbolLayer()
            hachura.setColor(QColor("#44a0e6"))
            hachura.setLineAngle(45)
            hachura.setDistance(2.5)

            symbol = QgsFillSymbol.createSimple({'color': '0,0,0,0', 'outline_color': '#44a0e6'})
            symbol.appendSymbolLayer(hachura)
            layer.setRenderer(QgsSingleSymbolRenderer(symbol))
            layer.triggerRepaint()

        return {}