# -*- coding: utf-8 -*-

"""
/***************************************************************************
 GeoCAR
                                 A QGIS plugin
 Cadastro Ambiental Rural
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-10
        copyright            : (C) 2026 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Prof Cazaroli e Leandro França'
__date__ = '2026-02-10'
__copyright__ = '(C) 2026 by Prof Cazaroli e Leandro França'

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
import os
from geocar.images.Imgs import *
import processing
from qgis.core import (QgsProject,
                       QgsMapLayer,
                       QgsWkbTypes,
                       QgsFeature,            
                       QgsCoordinateTransform, 
                       QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterEnum,
                       QgsProcessingUtils,
                       QgsProcessingException)

class linha_aux_Poligono(QgsProcessingAlgorithm):
    OUTPUT_FOLDER = 'OUTPUT_FOLDER'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return linha_aux_Poligono()

    def name(self):
        return 'linha_aux_Poligono'

    def displayName(self):
        return self.tr('Linha Auxiliar para Polígono')

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return ''

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/geocar.png'))

    def shortHelpString(self):
        txt = "Transforma Linha_Auxiliar em Polígono - caso de Rios, Estradas, Canais, etc. Quando necessário (caso de Goiás)"

        footer = '''<div>
                      <div align="center">
                      <img style="width: 100%; height: auto;" src="data:image/jpg;base64,'''+ CAR_GeoOne +'''
                      </div>
                      <div align="right">
                      <p align="right">
                      <a href="https://geoone.com.br/pvcar2/"><span style="font-weight: bold;">Conheça o curso de Cadastro Ambiental Rural (CAR)</span></a>
                      </p>
                      <p align="right">
                      <a href="https://portal.geoone.com.br/m/lessons/car"><span style="font-weight: bold;">Acesse seu curso na GeoOne</span></a>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
                      <p><i>"Mapeamento automatizado, fácil e direto ao ponto é na GeoOne!"</i></p>
                      </div>
                    </div>'''
        return txt + footer
    
    def initAlgorithm(self, config=None):
        # 1. Camada de Linha (Fonte)
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                'INPUT_LINE',
                self.tr('Selecione a Linha_Auxiliar'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        # 2. Largura total
        self.addParameter(
            QgsProcessingParameterNumber(
                'BUFFER_WIDTH',
                self.tr('Largura total (metros)'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=10.0
            )
        )

        # 3. Filtrar camadas RIO no projeto
        camadas_projeto = QgsProject.instance().mapLayers().values()
        self.camadas_rio = [
            lyr for lyr in camadas_projeto 
            if lyr.type() == QgsMapLayer.VectorLayer 
            and lyr.geometryType() == QgsWkbTypes.PolygonGeometry
            and 'RIO' in lyr.name().upper()
        ]
        
        nomes_rio = [lyr.name() for lyr in self.camadas_rio]
        if not nomes_rio:
            nomes_rio = [self.tr('Nenhuma camada RIO encontrada')]

        # 4. Caixa Combo para escolher o destino
        self.addParameter(
            QgsProcessingParameterEnum(
                'DESTINATION_RIO',
                self.tr('Escolha a camada RIO para receber o polígono'),
                options=nomes_rio
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        # 1. Recuperar parâmetros
        source_layer = self.parameterAsVectorLayer(parameters, 'INPUT_LINE', context)
        width = self.parameterAsDouble(parameters, 'BUFFER_WIDTH', context)
        buffer_distance = width / 2.0
        
        # Recuperar a camada RIO de destino do Enum
        idx = self.parameterAsEnum(parameters, 'DESTINATION_RIO', context)
        if not hasattr(self, 'camadas_rio') or not self.camadas_rio:
            raise QgsProcessingException('Nenhuma camada RIO disponível no projeto.')
        dest_layer = self.camadas_rio[idx]

        if feedback.isCanceled():
            return {}

        # 2. DISSOLVE (Garante feição única)
        feedback.pushInfo('Consolidando linha original...')
        dissolve_results = processing.run(
            "native:dissolve",
            {'INPUT': source_layer, 'OUTPUT': 'memory:dissolvida'},
            context=context, feedback=feedback, is_child_algorithm=True
        )

        # 3. BUFFER (Cria a camada temporária "Bordeada")
        feedback.pushInfo('Gerando geometria Bordeada...')
        buffer_results = processing.run(
            "native:buffer",
            {
                'INPUT': dissolve_results['OUTPUT'],
                'DISTANCE': buffer_distance,
                'END_CAP_STYLE': 1, # Flat
                'JOIN_STYLE': 0,
                'DISSOLVE': True,
                'OUTPUT': 'memory:Bordeada'
            },
            context=context, feedback=feedback, is_child_algorithm=True
        )

        # 4. COPIAR E COLAR COM COMPATIBILIDADE DE SRC
        bordeada_layer = QgsProcessingUtils.mapLayerFromString(buffer_results['OUTPUT'], context)
        
        if dest_layer and bordeada_layer:
            dest_layer.startEditing()
            
            # Preparar transformação de coordenadas caso os sistemas sejam diferentes
            # Isso impede que o polígono seja colado no lugar errado
            transform = QgsCoordinateTransform(bordeada_layer.crs(), dest_layer.crs(), QgsProject.instance())
            
            feicoes_adicionadas = 0
            for feat in bordeada_layer.getFeatures():
                # Criar uma nova feicao baseada na Bordeada
                nova_feicao = QgsFeature(feat)
                
                # Transformar a geometria para o SRC da camada destino (RIO)
                geom = nova_feicao.geometry()
                geom.transform(transform)
                nova_feicao.setGeometry(geom)
                
                # Tentar adicionar à camada destino
                if dest_layer.addFeature(nova_feicao):
                    feicoes_adicionadas += 1
            
            dest_layer.commitChanges()
            
            # Atualizar a visualização
            dest_layer.updateExtents()
            dest_layer.triggerRepaint()
            
            feedback.pushInfo(f'Sucesso! {feicoes_adicionadas} polígono(s) colado(s) em {dest_layer.name()}.')
        else:
            raise QgsProcessingException('Erro ao processar as camadas internas.')

        return {'STATUS': 'Concluído'}